fix: Mirroring modified files
Fixes error message when updating files:
requests.exceptions.RequestException: API call failed. This file does not exist.